language: nix
sudo: required
services:
- docker
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "./.owasp-dependency-check-db"
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
script:
- nix-shell --command "./gradlew assemble"
- nix-shell --command "./gradlew check"
- nix-shell --command "./gradlew install"
- nix-shell --command "timeout 300 ./.travis-cat_owasp_depcheck_reports.sh || true"
- nix-shell --command "./gradlew docker"
- if [[ ( "$TRAVIS_PULL_REQUEST" = "false" ) && (( "$TRAVIS_BRANCH" = "master" ) || ( "$TRAVIS_TAG" != "" )) ]]; then export TE_DEPLOY=true; fi
after_success:
- bash <(curl -s https://codecov.io/bash)
- nix-shell --command "./.travis-publishOnRelease.sh"
deploy:
  provider: script
  script: nix-shell --command "bash docker_push"
  on:
    condition: "$TE_DEPLOY != ''"
    all_branches: true
env:
  global:
    - # Environment variables for Docker 
    - secure: "JeCp69+B3veLfAv2WsYUN4iFfZmIb6McX2zWx5FJFzgQuNxsR+j4+lSCD75ATcnk25Qs9G53aS6Cu1f4WpL5Gd4W+8cpylCWq5e4mBB+7j3psgXnYIQ1l8tLpkVNRSZiEczMKo3lpjNzR+H6YtxtnAH6rBlEjnQpxRwXWKTQYhVWS5i+gttubuBpr6jqFNTBD6rpNOrpkxLR7zbQ4SX4inTY14D7G6Ik90rcLrdZCIbaS1olkMe2X+RMG0rboFxlKFShQwKc/cAGPMMzFEPFU4ysEwAPQjJYkurvn3s3GnzuG6NA4jsuQr4IHqhI+3+ZMcEldI4WVRnhBNO5d/a2+ab9g0wOtHjBP+5msiI02JpZiOxtNM8xZOKGa1zuBQcTexPmR/lNdpk9sQmczRD75PJPZIDi7OxcgUCtsVGVVH4WKuLfR06fVcMbAAB9ODP1EgSJuTZeMrRfeP1Pc+VMWuqU+J7AR46bJ4NfFg3i/OfEn8B+QRduqjqXvPEbmTAaMXhJiTmvvYwczR/eIgNPG8KaSu5eZCYs0NNrPKmMLEs6cjyeHBPEC5NiUyv/fhbq1Hv0ik6oXU8tyln+yaKMOO0mlWEG4rSGUaZ+babZprLAWV0sOgHz0rCcR/GGavC/pf3lhN4oVsv1uUMhoFtdf1ya3WF2KThnQux8uai5trg="
    - secure: "VpFWJS9vsRfkA9mWUWLG6W7xQMB4A22jx0gYXH+UUaxrvvx6F5IBSgDqfdKfYTZD6uwivc8xNOlPBPuMHG+sOnQRvkVqZEWTMWVz8ZA83Csv2lW+weqguCyuzau5NXEAEAxBECBmwAe8TtfZ1C8VnyWnc2tBxBS+9fyWRncETkxTL6NuX1PeTYgfcP4DmOKC729ED7/7XGH7j4P4yx5hIAZZdJQehkF9cjO0aD9lUtZGJ0s8o5j44FcDCZG42lpbfJr42nFSPRnDhpP4RfMNaAmluU0/x3F2VlyBA/wiVEu3C18SG5gGKn9Srw7KlzRJzjoOY8V6YKtDpnYYnmCSSXWuMNqF3RS10D45CWJ41yfcjsxEqLENW/hCBHW47IyZa2zrVpXwPotqUWdsiVye4s/uSEJoMvu/n8DBxf3w9A52QImUadsiV58rHbc9UsGes5x8prsWE4I+rOzid96i5pU7dzkl5FtXoNuthZDfslmTgy9TgAb99alsl38X0OLcf5L7KGUcaJrt9L0XPnZew5YnODbV0Cp4+Cxr//KAZbmFRE3UxFdfk9zI7qSqBF9+wbDpEDNrmTd+pROo15YrI20GXYJYVRmputigyJc+O5o2Jom1Fhhve9NF5TN8KRuvM3jyBDPsZhRq5vFrjVBUg9m+S/VARJL2Q7Ya4q/sra8="
    - # Bintray Environment variables for deployment
    - secure: "qhozVkZCG5IZH67pHBpZuFRYpOB/Nlm5kO9grodBwpVHQ/tYCu2cChDVRGUqCroOtqCCm3V35gC1C0EKcsqO3YXlDnb5F6IbgoLpZtW76EcJz1rIB1a+K0cP3Uy3smLUS98R9YGTVjcBl1eZCQ6yiM4X8pS4vlq1ctBjbHUpXDCa1/q8tQlPQB5Krjka1Sthg5fGUeYfuY+7NNDObI4hVw6CzVBB09e0pNv+rSzHGcsbtjS2R/Q9rm+gSTIgSYrwwrIRnTOBsJLfwEH4cHoR9JjKGr/X51d3kQgjbAWc1evZha+fbaA4Stga8r84iDCa2iCig7uW/opSBBuSQzq9RuNozQz7ml742qeqR4RsqpeFaTaoyJrzZphXupjjzq712NZ4WO9vrqfg8f1kO+7Ot21ge1r0D0rJYiSRXyCRQwTEsFJmaHK0EeAcDAuOwCbC6lpO6lOmRGFXnumvgDRZRGU0+L8Eqd/rxdLt4rr0RBt4L70WDUe+DR4wqVxz+LBiJgYCQGDnrq8+b1qxdXgRs6YDxDbpb+m4lUuRwCFVvmsRi7y/5zwmjAgY2gmfpm2fMWrZTXNO2IHXefJSQQZRQL9zZO81lnRfRrVxPlyiPpXRPcRA5rRhlWE3Scd4fEljFkj93srM2g/cVKSyEsJ7Jxf9gT1KER750fNCRNzQpoA="
    - secure: "Mi32Pbs6izQ2dXk7Dsbp1GPc5YAymkfaB+tIsSxtueNepwvnIMtdRFKMvnEzXnZQklCnyLyN58z+4gK6Iwm67WWS2lIT5EFZprnO/gFTmlHSWi2kqr84C3+jwIzZbpNIZrYKly/smG2nWy4tHswded3Im3s0TnMJPW9u6VhQSFUks76Ow2xssn/YdsOEos1HIK4BLeOEUVDssqT+DguI6ir37frGRi0LKYKoypSjS2u/uDHTbo4iN/ndsBS/6ptVgBmiZ0AM+oEdfQkbc0iJnqaCXEwXOC2116OhqafkwAHwnGT9zR0EXxzVRvEa74BBAEuf2nm6BwFSGBQDjA0kGH6rr+TbfEvxbBm/9axGCQ9lGVfmQqyS06I4I2WOyLENp/D/qMgN+5Yl0qjOshcvu/AR0pityuYfe7xiIjz05L8rdjUOILBMnLCRyieiQ/DXv5I2rCzWZAS63VkaighkGSm/25hgafIlb5l0EdUpRl2wYTH5ZqJ4UNEqmOGRVzWCfujGQ6vKEPO0dpJv5eKw9F/djmTkPtnSPpkqIzcfAc1MiSjnLbu6QHqOyQcPiQU0e5ps02EYmPThZKcAswj2ouoAkD9T9unD+eT9xo+WRhCjOtAoXSZTz7M2nbaBzzU0QJoUD7XzY5NYlhVy0xIaat70APO+PxK/s+5eSg0vxaI="
