language: nix
sudo: false
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
script:
- nix-shell --command "./gradlew assemble check install"
after_success:
- bash <(curl -s https://codecov.io/bash)
- nix-shell --command "./.travis-publishOnRelease.sh"
env:
  global: 
    - # Bintray Environment variables for deployment
    - secure: "qhozVkZCG5IZH67pHBpZuFRYpOB/Nlm5kO9grodBwpVHQ/tYCu2cChDVRGUqCroOtqCCm3V35gC1C0EKcsqO3YXlDnb5F6IbgoLpZtW76EcJz1rIB1a+K0cP3Uy3smLUS98R9YGTVjcBl1eZCQ6yiM4X8pS4vlq1ctBjbHUpXDCa1/q8tQlPQB5Krjka1Sthg5fGUeYfuY+7NNDObI4hVw6CzVBB09e0pNv+rSzHGcsbtjS2R/Q9rm+gSTIgSYrwwrIRnTOBsJLfwEH4cHoR9JjKGr/X51d3kQgjbAWc1evZha+fbaA4Stga8r84iDCa2iCig7uW/opSBBuSQzq9RuNozQz7ml742qeqR4RsqpeFaTaoyJrzZphXupjjzq712NZ4WO9vrqfg8f1kO+7Ot21ge1r0D0rJYiSRXyCRQwTEsFJmaHK0EeAcDAuOwCbC6lpO6lOmRGFXnumvgDRZRGU0+L8Eqd/rxdLt4rr0RBt4L70WDUe+DR4wqVxz+LBiJgYCQGDnrq8+b1qxdXgRs6YDxDbpb+m4lUuRwCFVvmsRi7y/5zwmjAgY2gmfpm2fMWrZTXNO2IHXefJSQQZRQL9zZO81lnRfRrVxPlyiPpXRPcRA5rRhlWE3Scd4fEljFkj93srM2g/cVKSyEsJ7Jxf9gT1KER750fNCRNzQpoA="
    - secure: "Mi32Pbs6izQ2dXk7Dsbp1GPc5YAymkfaB+tIsSxtueNepwvnIMtdRFKMvnEzXnZQklCnyLyN58z+4gK6Iwm67WWS2lIT5EFZprnO/gFTmlHSWi2kqr84C3+jwIzZbpNIZrYKly/smG2nWy4tHswded3Im3s0TnMJPW9u6VhQSFUks76Ow2xssn/YdsOEos1HIK4BLeOEUVDssqT+DguI6ir37frGRi0LKYKoypSjS2u/uDHTbo4iN/ndsBS/6ptVgBmiZ0AM+oEdfQkbc0iJnqaCXEwXOC2116OhqafkwAHwnGT9zR0EXxzVRvEa74BBAEuf2nm6BwFSGBQDjA0kGH6rr+TbfEvxbBm/9axGCQ9lGVfmQqyS06I4I2WOyLENp/D/qMgN+5Yl0qjOshcvu/AR0pityuYfe7xiIjz05L8rdjUOILBMnLCRyieiQ/DXv5I2rCzWZAS63VkaighkGSm/25hgafIlb5l0EdUpRl2wYTH5ZqJ4UNEqmOGRVzWCfujGQ6vKEPO0dpJv5eKw9F/djmTkPtnSPpkqIzcfAc1MiSjnLbu6QHqOyQcPiQU0e5ps02EYmPThZKcAswj2ouoAkD9T9unD+eT9xo+WRhCjOtAoXSZTz7M2nbaBzzU0QJoUD7XzY5NYlhVy0xIaat70APO+PxK/s+5eSg0vxaI="
