remoteRepoUrl: git@github.com:test-editor/test-editor-examples.git
applicationId: org.testeditor.web.backend.testexecution
localRepoFileRoot: managerRepo
server:
  applicationConnectors:
  - type: http 
    port: 10080
  adminConnectors:
  - type: http
    port: 10081
