#!/bin/sh
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push testeditor/testexecution:snapshot
if [[ $TRAVIS_TAG = v* ]]; then
  docker tag testeditor/testexecution:snapshot testeditor/testexecution:$TRAVIS_TAG
  docker push testeditor/testexecution:$TRAVIS_TAG
  docker tag testeditor/testexecution:snapshot testeditor/testexecution:latest
  docker push testeditor/testexecution:latest
fi
