remoteRepoUrl: file:///Users/jjelschen/projects/signal-iduna/language-examples
testExecutionManagerUrl: 'http://localhost:10080/testexecution/manager/workers'
workerUrl: 'http://localhost:11080'
applicationId: org.testeditor.web.backend.testexecution
localRepoFileRoot: workerRepo
server:
  applicationConnectors:
  - type: http 
    port: 11080
  adminConnectors:
  - type: http
    port: 11081
